### ISSUE TITLE
Mensaje: "En este momento no podemos conectar con tu contador"

### ISSUE THREAD

**Issue by EnricGarrigo** [trocotronic/edistribucion#11]
Cada ejecución del código en el fichero 'exemple.py' genera el mismo mensaje.
El ejemplo obtiene los datos del contador de forma correcta, pero la instrucciión "meter = edis.get_meter(cups)", siempre muestra el mismo mensaje.

![image](https://user-images.githubusercontent.com/41141131/199027816-0f2f1fef-008c-4a1f-976b-b2e65d5e87b4.png)

**Comment by trocotronic** [comment]
Es cosa de Edistribucion. A veces, no puede conectar con tu ICP.

No tiene solución por parte local.
