### ISSUE TITLE
Functions not working

### ISSUE THREAD

**Issue by nikuxic** [trocotronic/edistribucion#12]
Hi! I've been trying some functions such as get_cups and get_meter (as done in example.py). They work properly.
But, when I tried any other (get_list_cycles, get_meas, get_meas_interval, get_cups_info), I get always some error.

Can anybody try those methods again?

Thank you.

![imagen](https://user-images.githubusercontent.com/18567490/211350911-64349370-77ae-43f3-9a7f-a7d77a51a8fb.png)

**Comment by trocotronic** [comment]
Added `example2.py` that shows these commands.

**Comment by nikuxic** [comment]
Thanks a lot for the changes and the example.
I just want to say that [removing the path modification](https://github.com/trocotronic/edistribucion/commit/3333e71b82483894bd59ee6435c97193201f1406) does not work for me. I added it again locally.

![imagen](https://user-images.githubusercontent.com/18567490/211509616-9b67aef8-681b-4485-a689-d4f80ede2fcd.png)

**Comment by trocotronic** [comment]
You have to install in your path

`pip install .`

**Comment by nikuxic** [comment]
Aha!! Great!! Thank you
