### ISSUE TITLE
Add "setCredentials" and "logout" (or "dispose") methods

### ISSUE THREAD

**Issue by nikuxic** [trocotronic/edistribucion#13]
I'm using this API to access server using several credentials (different users).

Right now, credentials are "loaded" from 'credentials.py'. I need to change the credentials in runtime... Could it be possible to add a 'setCredentials(user, password)' method?
Also, if this 'setCredentials' method is defined (I've done it locally), when I call the 'login' method it keeps the previous session (for the previous credentials)... Could it be possible to add a 'logout' method? (or 'dispose' or 'close' ...)

**Comment by trocotronic** [comment]
I do not recommend playing with Edistribucion backend in that way, as you'll be surely banned forever if anomaly activity is detected. 
Said that, you can emulate what you asking for by removing/renaming `edistribucion.access` and `edistribucion.session`, which contain access credentials granted by the backend and session variables, all tied to the credentials set in `credentials.py`. If you rename both files and call a method (`get_cups()` or whatever), the API will login again by taking the user/password set in `credentials.py`. Therefore, you can alternate between a collection of `*.access` and `*.session` files to switch between users' portal.

Despite that, I would recommend you the correct way. Edistribucion has the capability to grant access to external users. For instance, an external user can grant you access to its portal and you will be able to access to its portal, all available with your own user/password. More info at https://zonaprivada.edistribucion.com/areaprivada/s/wp-authorizations

**Comment by nikuxic** [comment]
Aha!! Thanks a lot for all this information. I wasn't aware of that access for external. It will really help.
Again, thank you so much for being so quick and resolute responding.

**Comment by nikuxic** [comment]
Sorry to disturb again...

I got authorization to access as a external user. Through web I see the CUPS of the person that grant access to me. But using this API I don't :( . For example, '`edis.get_list_cups()`' returns an empty array...

Is it possible to access _authorized_ cups with this API?

Thank you so much.

PS: I'm not sure if this is the place to ask for this help.... Please, let me know

**Comment by trocotronic** [comment]
Do `get_all_cups()` or `get_cups()` return something?

**Comment by nikuxic** [comment]
They return something, but 'authorized' cups are not there

**Comment by nikuxic** [comment]
Just to give a hint...
In order to see the _authorized_ cups on web site, I have to choose the proper "persona o razón". Maybe that's what we need to do somewhere inside the API code.
![imagen](https://user-images.githubusercontent.com/18567490/212198737-c63ce86e-b869-4a7f-b87f-c366b08f2ef5.png)

**Comment by trocotronic** [comment]
I do not have a way to scrap multiple identities, but let me try one approach.
Can you paste what do you get on `get_login_info()`? Please anonymize it before pasting here.

**Comment by nikuxic** [comment]
Note that:

- I've changed all ids by replacing the last characters with '????'
- I've changed names and DNIs
- I have authorization from 2 users. But, in 'authList[0]' is myself (don't know why). 'authList[1]' is ok

**Comment by nikuxic** [comment]
Hi! Did you find any way to do it? Thank you.

**Comment by trocotronic** [comment]
Yes, seems that `get_login_info()` returns the ID to retrieve the linked CUPS. I need to work on how to implement it, as it will make a bit complex the retrieval.

**Comment by nachoplus** [comment]
Thank you for this great job!
Related to this, Can be avoided the load of credentials.py? I mean, this behaviour obligate to have a credentials.py in the working directory. I think that insted is better to have a login(user,passwd) method. More flexible for integrations

**Comment by trocotronic** [comment]
I pushed a new version with identities management. Now methods related with CUPS accept `vis` parameter. This parameter can be obtained via `get_identities()`, which will return a list of authorized supplies. If no parameter is provided, it takes the default identity.

Also `Edistribucion()` accept `login` and `password` arguments. If not provided, both are taken from `credentials.py` file.

Finally, no need to call `login()`, as it is called inside the initialization.

Refer to `example3.py` for examples on identity management.

**Note: I cannot not test identity management, as I do not own other supplies nor other people grants access to me. So, please report if you detect inconsistencies.**

**Comment by nachoplus** [comment]
I tried Edistribucion(login=user,password=password) but fail if not credentials.py exists in the working directory. May you catch the import error?. I mean:

```
try:
    import credentials
except:
    logging.warning("No credentials.py file found")

```
Thanks for suporting!

**Comment by trocotronic** [comment]
You should have a credentials file at least for fallback.

**Comment by nikuxic** [comment]
Hi!
I've just tried this new version 0.6.0 with my user and access to others.
It works perfectly!
Thank you so much!!
