### ISSUE TITLE
CUPS online data

### ISSUE THREAD

**Issue by nikuxic** [trocotronic/edistribucion#14]
Hi!

As far as I know, there is no way (through this API) to access to CUPS online.
I would like to know instant power and the total power consumed.

This can be accessed via web through https://zonaprivada.edistribucion.com/areaprivada/s/wp-online-access.

Have you scheduled to do so?

Thank you in advance.

**Comment by trocotronic** [comment]
Take a look on `example.py`.

**Comment by nikuxic** [comment]
Oops... Sorry, I didn't know it was the command...

But, it actually does not wotk in my case... When I call 'get_meter' it raises an exception.
Note: It happens using 'vis' or not to get 'cupsId'

![imagen](https://user-images.githubusercontent.com/18567490/215469602-230218f7-9a2c-47b7-ac38-d4674bf6192d.png)

**Comment by trocotronic** [comment]
Really strange. I cannot reproduce it. Can you paste the entire log? Ensure that .access and .session files are deleted before.

**Comment by nikuxic** [comment]
Oops... Sorry, My fault... :( I mistook cups['Id'] for cups['CUPS_Id']...
Well... I was using get_list_cups() instead of get_cups(), which results for 'Id' are different...

What I see is that **get_list_cups**() returns an array, where its elements have 'CUPS_Id' and 'Id' elements
On the other hand, **get_cups**() returns an array (within ['data']['lstCups']), where its elements have 'Id' (among others) but not 'CUPS_Id', and 'Id' is different than 'Id' for get_list_cups

Which is the difference? What is each used for?

![imagen](https://user-images.githubusercontent.com/18567490/215518483-001742c6-0927-470d-90e0-59c504d7b7d1.png)
