### ISSUE TITLE
Exception on "get_meas_interval()" -> 'lstData'

### ISSUE THREAD

**Issue by nikuxic** [trocotronic/edistribucion#18]
Hi,

I'm reading measurements data for a CUPS for 12/02/2023. "get_meas_interval()" raises an exception, whose text is 'lstData'.
Checking its data in edistribution website, I see that there is no data for that specific day.
See attached image and csv below (CUPS id has been replaced by 'ESXXXXXXXXX' for privacy). As you can see, there are no values for that day and first 3 hours of the following day (13/02/2023) for the field 'AE_kWh' in CSV file.

My question: Should it be interpreted as 0 kWh? Could it be done within the code of this repo?

Thank you.

[ESXXXXXXXXX_20230101_20230220_Horario.csv](https://github.com/trocotronic/edistribucion/files/10782142/ESXXXXXXXXX_20230101_20230220_Horario.csv)

![imagen](https://user-images.githubusercontent.com/18567490/220052856-17ba2b27-85ae-4e24-938d-b83b37d9985f.png)

**Comment by trocotronic** [comment]
Hard to say but probably yes. 

Closed as staled. Reopen if needed.
