### ISSUE TITLE
Reconectar ICP

### ISSUE THREAD

**Issue by jjprz** [trocotronic/edistribucion#2]
¿Sería posible realizar la Reconexión del ICP?

**Comment by polhenarejos** [comment]
Posiblemente sí se podría. Sin embargo no tengo manera de averiguarlo. En mi panel siempre está desactivada esta opción, imagino porque siempre tengo el ICP activado. Alguien tendría que bajarlo digitalmente en el contado (ni idea de cómo hacerlo), hacer log del tráfico de la web y enviármelo. Esto tendría que hacerlo con un PC portátil con 4G, ya que el ICP estaría bajado y no habría corriente en la casa. También valdría para una segunda residencia o similar.
El principal problema está en bajar el ICP en el contador, que si no se tiene acceso físicamente es complicado. La única forma sería provocar una sobretensión y forzar al ICP a desconectarse, pero esta vía no la recomiendo por los peligros que entraña.

**Comment by polhenarejos** [comment]
Posiblemente sí se podría. Sin embargo no tengo manera de averiguarlo. En mi panel siempre está desactivada esta opción, imagino porque siempre tengo el ICP activado. Alguien tendría que bajarlo digitalmente en el contado (ni idea de cómo hacerlo), hacer log del tráfico de la web y enviármelo. Esto tendría que hacerlo con un PC portátil con 4G, ya que el ICP estaría bajado y no habría corriente en la casa. También valdría para una segunda residencia o similar.
El principal problema está en bajar el ICP en el contador, que si no se tiene acceso físicamente es complicado. La única forma sería provocar una sobretensión y forzar al ICP a desconectarse, pero esta vía no la recomiendo por los peligros que entraña.

**Comment by trocotronic** [comment]
No hace falta hacer todo esto. He depurado con más detalle los eventos de la web y he subido una modificación. Por desgracia no tengo manera que testearlo.

**Comment by jjprz** [comment]
Voy a integrarlo e intentaré probarlo esta semana, me suele saltar con facilidad. Muchas gracias.
