### ISSUE TITLE
Error <<argument of type 'NoneType' is not iterable>>

### ISSUE THREAD

**Issue by bepece1** [trocotronic/edistribucion#26]
Buenas tardes,
Llevo unos 3-4 días con problemas en la ultima version (0.7.0), ¿os ocurre tambien a vosotros?

_> [INFO] Loading token scripts
> Traceback (most recent call last):
>   File "c:\temp\edistribucion-master20231016\example.py", line 11, in <module>
>     edis = Edistribucion()
>   File "c:\temp\edistribucion-master20231016\src\EdistribucionAPI\Edistribucion.py", line 133, in __init__
>     self.login()
>   File "c:\temp\edistribucion-master20231016\src\EdistribucionAPI\Edistribucion.py", line 240, in login
>     return self.__force_login()
>   File "c:\temp\edistribucion-master20231016\src\EdistribucionAPI\Edistribucion.py", line 312, in __force_login
>     self.__token = self.__get_token()
>   File "c:\temp\edistribucion-master20231016\src\EdistribucionAPI\Edistribucion.py", line 249, in __get_token
>     if ('auraConfig' in s.string):
> TypeError: argument of type 'NoneType' is not iterable_

Adjunto fichero con log completo.

Gracias por la ayuda.

Un saludo.
[log_edistribucion.txt](https://github.com/trocotronic/edistribucion/files/12918459/log_edistribucion.txt)

**Comment by bepece1** [comment]
@trocotronic  Gracias por la rapida actuacion, pero... sigue dandome un error. ¿que puede ser?

![image](https://github.com/trocotronic/edistribucion/assets/38904049/4c57e677-eccc-447d-8390-ae5ee5486301)

He revisado, por si las moscas, la web oficial y funciona correctamente:
![image](https://github.com/trocotronic/edistribucion/assets/38904049/8f99aeb6-6bbb-4008-bad2-2fe47d4585ed)

**Comment by trocotronic** [comment]
Es raro. Cuando subí los cambios funcionaba. Parece que estos días están cambiando cosas del backend. Mira de usar el context que dicen en #27 mientras
Cuando tenga un hueco lo miro.

**Comment by bepece1** [comment]
> Es raro. Cuando subí los cambios funcionaba. Parece que estos días están cambiando cosas del backend. Mira de usar el context que dicen en #27 mientras Cuando tenga un hueco lo miro.

Con este contexto funciona correctamente:  https://github.com/trocotronic/edistribucion/issues/27#issuecomment-1771320686

self.__context = '{"mode":"PROD","fwuid":"MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMi0zLjAuNA","app":"siteforce:communityApp","loaded":{"APPLICATION@markup://siteforce:loginApp2":"gYLnBR7JPOzHCaMCDxTL3w"},"dn":[],"globals":{},"uad":false}'

**Comment by trocotronic** [comment]
Corregido en 89c9664
