### ISSUE TITLE
token methode as changed

### ISSUE THREAD

**Issue by dmachadol** [trocotronic/edistribucion#27]
in def __force_login(self, recursive=False):

change:
 self.__context = '{"mode":"PROD","fwuid":"LU1oNENmckdVUXNqVGtLeG5odmktZ2Rkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMS0zLjAuNA","app":"siteforce:communityApp","loaded":{"APPLICATION@markup://siteforce:communityApp":"8srl03VqKMnukxbiM5O73w"},"dn":[],"globals":{},"uad":false}'

by:
 self.__context = '{"mode":"PROD","fwuid":"LU1oNENmckdVUXNqVGtLeG5odmktZ2Rkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMS0zLjAuNA","app":"siteforce:communityApp2","loaded":{"APPLICATION@markup://siteforce:communityApp2":"8srl03VqKMnukxbiM5O73w"},"dn":[],"globals":{},"uad":false}'

now authenticate but still have issues

**Comment by moralespetit** [comment]
doesn't work for me :
r.text : 
{"event":{"descriptor":"markup://aura:invalidSession","attributes":{"values":{}},"eventDef":{"descriptor":"markup://aura:invalidSession","t":"APPLICATION","xs":"I","a":{"newToken":["newToken","aura://String","I",false]}}},"exceptionMessage":"0DM1o000000g0SG","exceptionEvent":true}

there is not the ['events'][0]['attributes']['values']['url']

**Comment by dmachadol** [comment]
try, with:
self.__context = '{"mode":"PROD","fwuid":"MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMi0zLjAuNA","app":"siteforce:communityApp","loaded":{"APPLICATION@markup://siteforce:loginApp2":"gYLnBR7JPOzHCaMCDxTL3w"},"dn":[],"globals":{},"uad":false}'

**Comment by moralespetit** [comment]
@dmachadol  WORKS !! thank you so much 
Will we need to change this context every week?

**Comment by dmachadol** [comment]
I think  no. May be e-distribucion are processing changes this days.

**Comment by trocotronic** [comment]
I used loginApp in the past and some methods were rejected. I am not sure what happens with communityApp2 or loginApp2 but there should be a clever way to catch up the right context somehow.

**Comment by bepece1** [comment]
> try, with: self.__context = '{"mode":"PROD","fwuid":"MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMi0zLjAuNA","app":"siteforce:communityApp","loaded":{"APPLICATION@markup://siteforce:loginApp2":"gYLnBR7JPOzHCaMCDxTL3w"},"dn":[],"globals":{},"uad":false}'

With this context, works righly

Thank for share

**Comment by moralespetit** [comment]
Hi again, 
the context https://github.com/trocotronic/edistribucion/issues/27#issuecomment-1772588246 is not woking more for me . 

I `r = self.__get_url(self.__dashboard+'r=1&other.LightningLoginForm.login=1',post=data)
returns :  
*/{"event":{"descriptor":"markup://aura:clientOutOfSync",
 "eventDef":{"descriptor":"markup://aura:clientOutOfSync","t":"APPLICATION","xs":"I"}},
 "exceptionMessage":"Framework has been updated. Expected: MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMy0zLjAuNA 
 Actual: MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMi0zLjAuNA","exceptionEvent":true}/*ERROR*/

`

So , I changed the context to : 
`self.__context = '{"mode":"PROD","fwuid":"MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuMy0zLjAuNA","app":"siteforce:communityApp","loaded":{"APPLICATION@markup://siteforce:loginApp2":"gYLnBR7JPOzHCaMCDxTL3w"},"dn":[],"globals":{},"uad":false}'
        `
and works fine again

Do you think that is possible to do this context change dinamic? getting the new r['Actual'] context code ?

Best regards

**Comment by trocotronic** [comment]
Yep, I pushed a commit with the new fwuid.

I'll try to figure out how to take the correct `context`. Any contribution is welcomed.
