### ISSUE TITLE
New funtion to get data between two dates.

### ISSUE THREAD

**Issue by dmachadol** [trocotronic/edistribucion#28]
please add to EdistribucionAPI.py

    def  get_meas_dates(self, cont, start, end):
        action = EdistribucionMessageAction(
            965,
            "WP_Measure_v3_CTRL/ACTION$getChartPointsByRange",
            "WP_Measure_Detail_Filter_Advanced_v3",
            {"contId":""+cont['Id']+"","type":"4","startDate":""+start+"","endDate":""+end+""}
        )
        r = self.__run_action_command(action)
        if 'data' in r.keys():
            if 'lstData' in r['data'].keys():
                return r['data']['lstData']
        return []

**Comment by trocotronic** [comment]
Can you send a PR?

**Comment by dmachadol** [comment]
I'm sorry, that's a PR? I'm not used to using github
--

 ***@***.***>

 ***@***.***> ***@***.***> ***@***.***>



Daniel Machado Lopez
***@***.***

 ***@***.***>***@***.*** ***@***.***>

C/ Oviedo, 46 - 17005 Girona (Spain)
902 733 822 -  ***@***.***>www.aerisnavigo.com <http://www.aerisnavigo.com/>

**Comment by trocotronic** [comment]
PR=Pull Request. You first fork this repo onto your account, create a new branch, push your changes to that branch and Github will let you to send a PR to the original repo.

**Comment by dmachadol** [comment]
ok, I not sure if I do a gitclone or download directly. I try to do a PR in new request.

--

 ***@***.***>

 ***@***.***> ***@***.***> ***@***.***>



Daniel Machado Lopez
***@***.***

 ***@***.***>***@***.*** ***@***.***>

C/ Oviedo, 46 - 17005 Girona (Spain)
902 733 822 -  ***@***.***>www.aerisnavigo.com <http://www.aerisnavigo.com/>

**Comment by dmachadol** [comment]
> PR=Pull Request. You first fork this repo onto your account, create a new branch, push your changes to that branch and Github will let you to send a PR to the original repo.

Done, I close this issue, there are included into PR. Thanks.
