### ISSUE TITLE
setting a rol

### ISSUE THREAD

**Issue by dmachadol** [trocotronic/edistribucion#29]
this functions able to change Rol, get authoriced persons and authoriced cups, in Edistribution when you have multiples Rols and represetantion profiles.

Add to EdistribucionAPI.py:

    def set_rol(self, visId):
        action = EdistribucionMessageAction(
            595,
            "WP_ProfileMenu_CTRL/ACTION$saveRole",
            "WP_ProfileMenu",
            {"visId":""+visId+""}
        )
        r = self.__run_action_command(action)
        return r

    def get_authorized(self):
        action = EdistribucionMessageAction(
            390,
            "WP_Monitor_CTRL/ACTION$getLoginInfo",
            "WP_Monitor",
            {"serviceNumber":"S001"}
        )
        r = self.__run_action_command(action)
        return r['authList']

    def get_authorized_cups(self, id):
        action = EdistribucionMessageAction(
            339,
            "WP_Measure_v3_CTRL/ACTION$getListCups",
            "WP_Measure_List_v4",
            {"sIdentificador":""+id+""}
        )
        r = self.__run_action_command(action)
        return r

**Comment by trocotronic** [comment]
Seems code is cut at the end. Can you send a PR?

**Comment by dmachadol** [comment]
I don kwon to add a PR, this code I added at botton of EdistribucionAPI.py

**Comment by dmachadol** [comment]
add a sample main.py code

    print ("Connectant a e-distribucio... ", end='', flush=True)
    cursor = db.cursor(buffered = True)
    cursor_ins = db.cursor(buffered = True)
    edis = Edistribucion(USER, PASSWORD, debug_level=logging.CRITICAL)
    edis.login()
    print ("Ok.")
    print ("Seleccionant ROL DPS Giroconsulting")
    r = edis.set_rol('a5U2o000001I6MwEAK') # Set Rol DPS Giroconsulting
    print ("Consultant llista de subministres autoritzats... ", end='', flush=True)
    registros_ins = 0
    clientes_autorizados = edis.get_authorized()
    for cliente in clientes_autorizados:
        r = edis.get_authorized_cups(cliente['value'])
        cups = r['data']['lstCups']
