### ISSUE TITLE
json como única salida.

### ISSUE THREAD

**Issue by alsak0de** [trocotronic/edistribucion#5]
Enhorabuena por este pedazo de scrapper y gracias por compartirlo.

¿hay alguna manera de hacer una ejecución 'poco verbosa' y que retorne solo el json final de {meter} ?

Gracias

**Comment by trocotronic** [comment]
En breve lo pondré como método configurable. 
Mientrastanto puedes editar la línea 14 de la API y donde pone logging.INFO cambiarlo por logging.ERROR.

**Comment by alsak0de** [comment]
Gracias!!

Lo que he hecho es, de momento, ejecutarlo así:

$ ./example.py | grep Meter | cut -c9- >> meter_log.txt

Lo que me deja en el fichero solo la salida del meter como:

{'data': {'potenciaActual': 4.45, 'totalizador': '21.891', 'estadoICP': 'Abierto', 'potenciaContratada': 6.6, 'showLabel': False, 'percent': '67,42%'}, 'hasWarning': False, 'rejectPromise': False}

**Comment by alsak0de** [comment]
Gracias; he hecho un fork para modificar la línea.

**Comment by trocotronic** [comment]
Prueba a llamar al constructor Edistribucion(user=user,password=password,debug_level=logging.CRITICAL)
